### ISSUE TITLE
Allow passing in stack name

### ISSUE THREAD

**Issue by manchuck** [DavidWells/serverless-manifest-plugin#1]
If you change the name of the stack created by serverless, this plug fails. This is because it is reading the name from the ``service`` key. The following example demonstrates how to reproduce:

serverless.yml
```yml
service: fizz

provider:
  stackName: buzz
```

output
```
sls manifest
Unhandled rejection ServerlessError: Stack with id buzz does not exist
    at promise.catch.err (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:295:11)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by DavidWells** [comment]
The name of the stack is `buzz` (resolving to `buzz-{stage}`)?

I'm grabbing stack name here: https://github.com/DavidWells/serverless-manifest-plugin/blob/master/src/index.js#L45

We might need logic around this line https://github.com/DavidWells/serverless-manifest-plugin/blob/master/src/index.js#L49 to account for the custom stack name

**Comment by manchuck** [comment]
@DavidWells Correct that is what I'm seeing.  I would be a bit cautious in assuming that it is ``buzz-{stage}``. I could set up the stack name like the following:

```yml
service: fizz

provider:
  stackName: buzz-${self:custom.type}-${self:provider.stage}
```
(which is really what I'm doing in this case)

Doing some digging It looks like we can use the data from the AWS provider: 
https://github.com/serverless/serverless/blob/master/lib/plugins/aws/provider/awsProvider.js#L580

I'm going to play around a bit and see If I can get a PR built.

**Comment by DavidWells** [comment]
Sounds good to me!

If customstack name use it otherwise default to the default service name.

Thanks for looking into this!

**Comment by manchuck** [comment]
see #2

**Comment by DavidWells** [comment]
Thanks for the fix 🎉

```
npm i serverless-manifest-plugin@0.0.9
```
