### ISSUE TITLE
feature request: disable post-deploy hook

### ISSUE THREAD

**Issue by theburningmonk** [DavidWells/serverless-manifest-plugin#11]
There's an incompatibility with plugins that auto-generates some handler files, like the `serverless-lumigo` plugin, which creates wrapper modules during deployment and then deletes them. 

So when the manifest plugin runs after that, it errors, e.g.

```
  Error --------------------------------------------------
 
  Error: File "_lumigo/createProfile.js" not found. /Users/yancui/SourceCode/FattalSPRL/nova-sports-app/NovaSportsBackend/graphql-api/_lumigo/createProfile.js missing
```

But I only really need to generate the manifest before I run my tests, which works just fine.

It would be great to have an option to `disableAutoGeneration` or something like that which turns off the post-deployment hook.

**Comment by DavidWells** [comment]
Interesting... 

So you have a plugin that is generating temporary functions that are deployed but then the code is deleted locally? 

What’s the reason they are deleted? 

One thing the manifest plugin does is scans all your deployed dependancies & lists them, this would include lumingo sdk etc.

I see the limingo folder there as well. Does that entire folder get deleted after deploys?

**Comment by theburningmonk** [comment]
They're deleted after the deployment because they don't belong to the repo per se.

Say, a customer tries out lumigo, deploys their project, and if we don't delete those generated modules, what do they do with them? Do they delete them manually? Do they leave them there, would someone else look at them later and think, mm.. weird, what are those things, we don't reference them from our `serverless.yml` anywhere. And if the client decides not to continue with Lumigo after the free trial, then there's even less context as to what those files are for. So, there's really no up-side for keeping them around, at least none that I could think of.

Even the Lumigo tracer SDK is install on pre-package, and then uninstall on post-deployment, and the only place the SDK is referenced is in the temporary, generated files. So from a user's perspective, there's no change to your project besides installing the plugin and configuring your lumigo_token in the `serverless.yml`.

The entire folder gets deleted, and the lumigo_tracer is also uninstalled as well.

**Comment by DavidWells** [comment]
Makes sense. What about jamming the functions into the .serverless hidden folder?

The `.serverless` folder gets blown away every time there is a new deployment.

Alternatively, there is a utility I created that automagically adds folders to user's gitignore files too if that helps here. https://github.com/DavidWells/serverless-manifest-plugin/blob/master/src/utils/gitignore.js#L86 you could add `lumigo` folder to gitignore

Presenting these alternatives b/c I was to keep the options here to a minimum 😅

**Comment by theburningmonk** [comment]
The wrapped functions needs to be bundled, is the content of .serverless folder bundled into the s3 artefact?

**Comment by DavidWells** [comment]
Nope. Anything extra placed in the `.serverless` folder gets blown away every deployment.

Then the folder `.serverless` gets recreated and only the function contents are deployed from what I can see. (No manifest.json in the function s3 buckets)

You could write to `.serverless/lumigo/createProfile.js` if you want these to be automatically deleted/regenerated by the framework.

I will add the `disableAutoGeneration` for ya though. I might not document it tho. 😃

**Comment by DavidWells** [comment]
Just released a new version with `disablePostDeployGeneration` option in `serverless-manifest-plugin@1.0.4`

```yml
custom:
  manifest:
    disablePostDeployGeneration: true
```

This will disable the manifest creation after `sls deploy` is ran. To generate the manifest with this option on, you will need to run `sls manifest` command

**Comment by theburningmonk** [comment]
I think I might have misrepresented the purpose of those temporary files. So those temporary flies the lumigo plugin spits out ARE the function handler modules that will be shipped:

![image](https://user-images.githubusercontent.com/546969/80792063-ccc2e700-8b93-11ea-8042-40abb136a48a.png)

So they need to be included in the zip.

If I understand you correctly, they can't live in the `.serverless` in that case.

And, thanks for adding the option!
