### ISSUE TITLE
Custom Domain not using serverless-domain-manager plugin

### ISSUE THREAD

**Issue by nickwillan** [DavidWells/serverless-manifest-plugin#13]
Hi @DavidWells, we use serverless-manifest-plugin in many of our repos, and it's great.  However, we stopped using serverless-domain-manager plugin for various reasons, but liked the integration with that plugin as it changed the URLs if a custom domain was used.  We can use the `postProcess` to overwrite our domain, but was curious if you'd accept a PR that allows a serverless-manifiest-plugin parameter to set the domain name, instead of a deep integration with serverless-domain-manager.

Thanks,
Nick Willan
Trend Micro

**Comment by DavidWells** [comment]
I've moved away from the `serverless-domain-manager` as well.

I'm open to this 😃

The other thing I'm trying to figure out is how to populate appSync URLs if the stack has them... that's for another issue though
