### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by MikeSpitz** [DavidWells/serverless-manifest-plugin#3]
Hey, are you able to clarify which license this uses so I know if I can open a PR/modify locally etc.

**Comment by MikeSpitz** [comment]
Buump @DavidWells - could you take a look at this please? Otherwise I need to re-work what I have and would rather use what you've made!

**Comment by DavidWells** [comment]
Sorry for delay here. 

Added https://github.com/DavidWells/serverless-manifest-plugin/blob/master/LICENSE and updated this plugin with more features
